EVALUATE
UNION (
    ROW (
        "Table", "Product",
        "Column", "ProductKey",
        "Count", COUNT ( 'Product'[ProductKey] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[ProductKey] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[ProductKey] ),
        "Min", MIN ( 'Product'[ProductKey] ),
        "Max", MAX ( 'Product'[ProductKey] ),
        "Median", MEDIAN ( 'Product'[ProductKey] ),
        "Mean", AVERAGE ( 'Product'[ProductKey] ),
        "Standard Deviation", STDEV.P ( 'Product'[ProductKey] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'Product', 'Product'[ProductKey] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[ProductKey], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[ProductKey], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'Product'[ProductKey], 0.25 ),
        "P75", PERCENTILE.INC ( 'Product'[ProductKey], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Product Code",
        "Count", COUNT ( 'Product'[Product Code] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Product Code] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Product Code] ),
        "Min", MIN ( 'Product'[Product Code] ),
        "Max", MAX ( 'Product'[Product Code] ),
        "Median", MEDIAN ( 'Product'[Product Code] ),
        "Mean", AVERAGE ( 'Product'[Product Code] ),
        "Standard Deviation", STDEV.P ( 'Product'[Product Code] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'Product', 'Product'[Product Code] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[Product Code], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[Product Code], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'Product'[Product Code], 0.25 ),
        "P75", PERCENTILE.INC ( 'Product'[Product Code], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Product Name",
        "Count", COUNT ( 'Product'[Product Name] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Product Name] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Product Name] ),
        "Min", MIN ( 'Product'[Product Name] ),
        "Max", MAX ( 'Product'[Product Name] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Manufacturer",
        "Count", COUNT ( 'Product'[Manufacturer] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Manufacturer] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Manufacturer] ),
        "Min", MIN ( 'Product'[Manufacturer] ),
        "Max", MAX ( 'Product'[Manufacturer] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Brand",
        "Count", COUNT ( 'Product'[Brand] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Brand] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Brand] ),
        "Min", MIN ( 'Product'[Brand] ),
        "Max", MAX ( 'Product'[Brand] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Color",
        "Count", COUNT ( 'Product'[Color] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Color] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Color] ),
        "Min", MIN ( 'Product'[Color] ),
        "Max", MAX ( 'Product'[Color] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Weight",
        "Count", COUNT ( 'Product'[Weight] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Weight] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Weight] ),
        "Min", MIN ( 'Product'[Weight] ),
        "Max", MAX ( 'Product'[Weight] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Weight Unit Measure",
        "Count", COUNT ( 'Product'[Weight Unit Measure] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Weight Unit Measure] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Weight Unit Measure] ),
        "Min", MIN ( 'Product'[Weight Unit Measure] ),
        "Max", MAX ( 'Product'[Weight Unit Measure] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Unit Cost",
        "Count", COUNT ( 'Product'[Unit Cost] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Unit Cost] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Unit Cost] ),
        "Min", MIN ( 'Product'[Unit Cost] ),
        "Max", MAX ( 'Product'[Unit Cost] ),
        "Median", MEDIAN ( 'Product'[Unit Cost] ),
        "Mean", AVERAGE ( 'Product'[Unit Cost] ),
        "Standard Deviation", STDEV.P ( 'Product'[Unit Cost] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'Product', 'Product'[Unit Cost] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[Unit Cost], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[Unit Cost], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'Product'[Unit Cost], 0.25 ),
        "P75", PERCENTILE.INC ( 'Product'[Unit Cost], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Unit Price",
        "Count", COUNT ( 'Product'[Unit Price] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Unit Price] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Unit Price] ),
        "Min", MIN ( 'Product'[Unit Price] ),
        "Max", MAX ( 'Product'[Unit Price] ),
        "Median", MEDIAN ( 'Product'[Unit Price] ),
        "Mean", AVERAGE ( 'Product'[Unit Price] ),
        "Standard Deviation", STDEV.P ( 'Product'[Unit Price] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'Product', 'Product'[Unit Price] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[Unit Price], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'Product', MOD ( 'Product'[Unit Price], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'Product'[Unit Price], 0.25 ),
        "P75", PERCENTILE.INC ( 'Product'[Unit Price], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Available Date",
        "Count", COUNT ( 'Product'[Available Date] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Available Date] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Available Date] ),
        "Min", MIN ( 'Product'[Available Date] ),
        "Max", MAX ( 'Product'[Available Date] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'Product', 'Product'[Available Date] = 0 ) ), 0 ),
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", DATEDIFF ( MIN ( 'Product'[Available Date] ), MAX ( 'Product'[Available Date] ), DAY ),
        "Range in Months", DATEDIFF ( MIN ( 'Product'[Available Date] ), MAX ( 'Product'[Available Date] ), MONTH ),
        "Range in Years", DATEDIFF ( MIN ( 'Product'[Available Date] ), MAX ( 'Product'[Available Date] ), YEAR )
    ),
    ROW (
        "Table", "Product",
        "Column", "Subcategory",
        "Count", COUNT ( 'Product'[Subcategory] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Subcategory] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Subcategory] ),
        "Min", MIN ( 'Product'[Subcategory] ),
        "Max", MAX ( 'Product'[Subcategory] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Product",
        "Column", "Category",
        "Count", COUNT ( 'Product'[Category] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Product'[Category] ),
        "Null Count", COUNTROWS ( 'Product' ) - COUNT ( 'Product'[Category] ),
        "Min", MIN ( 'Product'[Category] ),
        "Max", MAX ( 'Product'[Category] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    )
)