//Day 15 - Oldest captain/s
DEFINE
    VAR _CaptainFilter =
        TREATAS( { 1 }, 'player_appearances'[captain] )
    MEASURE 'player_appearances'[Player Age] =
        VAR _Player = SELECTEDVALUE( 'player_appearances'[player_id] )
        VAR _BirthDate =
            LOOKUPVALUE(
                'players'[birth_date],
                'players'[player_id],
                _Player
            )
        VAR _MatchDate =
            SELECTEDVALUE( 'player_appearances'[match_date] )
        RETURN
            DATEDIFF( _BirthDate, _MatchDate, DAY )

EVALUATE
{
    CONCATENATEX(
        TOPN(
            1,
            SUMMARIZECOLUMNS(
                'player_appearances'[match_id],
                'player_appearances'[player_id],
                'player_appearances'[match_date],
                'player_appearances'[given_name],
                'player_appearances'[family_name],
                _CaptainFilter,
                "@Player Age", [Player Age]
            ),
            [Player Age], DESC
        ),
        CONCATENATE(
            CONCATENATE( 'player_appearances'[given_name], " " ),
            'player_appearances'[family_name]
        ),
        ", ",
        'player_appearances'[given_name]
    )
}